config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :users do
    member do
      get 'add' ,to: 'users#add'
      patch 'update_balance', to: 'users#update'
      get "mypokemons", to:'users#mypokemons'
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  end

  resources :pokemons
  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :pokemons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        @pokemons = Pokemon.all
    end

    def show
        @pokemon = Pokemon.find(params[:id])
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    def add
        @user = current_user
    end

    def update
    @user = current_user

    amount = params[:amount].to_i

    if amount > 0
      # Ajoute la valeur à la balance de l'user
      @user.balance += amount

      if @user.save
        flash[:success] = "Ajout de #{amount} à la balance réussi."
      else
        flash[:error] = "Erreur lors de la mise à jour de la balance."
      end
    else
      flash[:error] = "La valeur doit être supérieure à zéro."
    end

    # Retour
    redirect_to root_path
  
    end

    def mypokemons
        @user_pokemons = current_user.pokemons
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokécoin</title>
</head>
<body>

<h1>Pokécoin</h1>

<% if user_signed_in? %>
  <p>Vous êtes connecté en tant que <%= current_user.email %>.</p>

  <%= link_to 'Ajouter de l"argent', add_user_path(current_user) %><br>
   <%= link_to 'Voir les pokemon', pokemons_path %><br>
   <%= link_to 'Mes Pokémon', mypokemons_user_path(current_user) %>
<p>portefeuille :  <%= current_user.balance %> euro</p>

  <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>

<% else %>
  <%= link_to 'Inscription', new_user_registration_path %><br>
  <%= link_to 'Connexion', new_user_session_path %>
<% end %>



</body>
</html>

app/views/pokemons/index.html.erb
<h1>Tous Nos Pokémon</h1>
<h2>  <%= current_user.email %> euro</h2>
<p>portefeuille :  <%= current_user.balance %> euro</p>
<ul>
  <% @pokemons.each do |pokemon| %>
    <li>
      <strong>Nom :</strong> <%= pokemon.name %><br>
      <%
=begin%>
 <strong>Image :</strong> <%= image_tag(pokemon.imagepath, alt: pokemon.name, width: 100) %><br> 
<%
=end%>
      
      <strong>Prix :</strong> <%= pokemon.price %> $
      <br>
        <%= link_to 'Voir ce Pokémon', pokemon_path(pokemon) %>
      <br>
    </li>
  <% end %>
</ul>

 <%= link_to 'retour', root_path %><br>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>
<h2>  <%= current_user.email %> euro</h2>
<p>portefeuille :  <%= current_user.balance %> euro</p>

<p><strong>Poids :</strong> <%= @pokemon.weight %> kg</p>
<p><strong>Hauteur :</strong> <%= @pokemon.height %> m</p>
<p><strong>Prix :</strong> <%= @pokemon.price %> $</p>

<% if current_user.balance >= @pokemon.price %>
 <p>Acheter!</p>
 
<% else %>
  <p>Vous n'avez pas assez d'argent pour ce Pokémon.</p>
 <%= link_to 'Ajouter de l"argent', add_user_path(current_user) %><br>
<% end %>

<%= link_to 'Retour à la liste des Pokémon', pokemons_path %>

app/views/users/add.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajouter de l'argent</title>
</head>
<body>

<h1>Bienvenue, <%= current_user.email %> !</h1>
<p>portefeuille :  <%= current_user.balance %> euro</p>
<%= form_for(current_user, url: update_balance_user_path) do |f| %>
  <div class="field">
    <%= f.label :amount, "Montant à ajouter" %>
  <%= number_field_tag :amount, nil, step: 1 %>
  
  </div>
  <div class="actions">
    <%= f.submit "Ajouter de l'argent" %>

  </div>
<% end %>
 <%= link_to 'retour', root_path %><br>

</body>
</html>

app/views/users/mypokemons.html.erb
<h1>Mes Pokémon</h1>

<ul>
  <% @user_pokemons.each do |pokemon| %>
    <li>
      <strong>Nom du Pokémon :</strong> <%= pokemon.name %><br>
      <strong>Image :</strong> <%= pokemon.imagepath %><br>
      <strong>Poids :</strong> <%= pokemon.weight %> kg<br>
      <strong>Hauteur :</strong> <%= pokemon.height %> m<br>
      <strong>Prix :</strong> <%= pokemon.price %> $<br>
    </li>

    <p>VENDRE CE POKEMON</p>
     <%= link_to 'retour', root_path %><br>
  <% end %>
</ul>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Déconnexion réussie</title>
</head>
<body>

<h1>Déconnexion réussie</h1>
<p>Vous êtes bien déconnecté.</p>

<a href="<%= root_path %>">Retour à la page d'accueil</a>

</body>
</html>